### ISSUE TITLE
Client is not consuming message

### ISSUE THREAD

**Issue by 15I** [amqphub/quarkus-qpid-jms#6] opened 2020-03-15 00:10 UTC
The client with activated tracing is not receiving a message from a JMS broker (**ActiveMQ Classic**) when the transformer transport option on the transportConnector set to "jms"
<transportConnector name="amqp" uri="amqp://localhost:5672?transport.transformer=jms"/> 

![image](https://user-images.githubusercontent.com/11261668/76692626-758ea480-662f-11ea-877a-d3ca8dacbf33.png)

**Comment by gemmellr** [comment] 2020-03-15 00:46
If it works when the broker isnt using its 'jms' transformer then the issue is in the broker. If thats the case, please close this and report the issue there.

**Comment by 15I** [comment] 2020-03-15 01:09
It works when "x-opt-qpid-tracestate" is not propagated.

**Comment by gemmellr** [comment] 2020-03-15 10:26
The issue likely relates to the brokers handling of that annotation.

If you think there is a client issue please provide a basic reproducer of what you are doing.

**Closed as completed** 2020-03-24 23:20 UTC
